actions:
- actions:
  - inputs:
    - id: config
      var: i
    outputs:
    - id: config_out
      var: output_config
    service: /fsx/ElastiFlow/deploy/runners/run_hpo.py
    type: execute
  enumerator: i
  input: input_config
  type: for
  yieldToInput: output_config
api: 4.7.0
config:
  mesh: wide_resnet101_2
  workflowIterations: 4
constraints:
  budget: 2.15
  chains: 3
  deadline: 6717.39
  tinydaIterations: 16
id: hpo-f4815881
vars:
- id: input_config
  value:
    batch_size: 128
    epochs: 16
    learning_rate: 0.0622
    model: wide_resnet101_2
    momentum: 0.96
    next_trials: 3
