actions:
- actions:
  - inputs:
    - id: config
      var: i
    outputs:
    - id: config_out
      var: output_config
    service: /fsx/Vortex-mid/Vortex-moldable-sched/service/run_hpo.py
    type: execute
  enumerator: i
  input: input_config
  type: for
  yieldToInput: output_config
api: 4.7.0
config:
  mesh: convnext_large
  workflowIterations: 5
constraints:
  budget: 15.43
  chains: 2
  deadline: 38051.17
  tinydaIterations: 8
id: hpo-a82342ac
vars:
- id: input_config
  value:
    batch_size: 64
    epochs: 8
    learning_rate: 0.0079
    model: convnext_large
    momentum: 0.93
    next_trials: 2
