actions:
- actions:
  - inputs:
    - id: config
      var: i
    outputs:
    - id: config_out
      var: output_config
    service: /fsx/Vortex-mid/Vortex-moldable-sched/service/run_hpo.py
    type: execute
  enumerator: i
  input: input_config
  type: for
  yieldToInput: output_config
api: 4.7.0
config:
  mesh: wide_resnet101_2
  workflowIterations: 3
constraints:
  budget: 19.99
  chains: 3
  deadline: 89829.91
  tinydaIterations: 4
id: hpo-da47d1ab
vars:
- id: input_config
  value:
    batch_size: 64
    epochs: 4
    learning_rate: 0.0758
    model: wide_resnet101_2
    momentum: 0.92
    next_trials: 3
