actions:
- actions:
  - inputs:
    - id: config
      var: i
    outputs:
    - id: config_out
      var: output_config
    service: /fsx/Vortex-mid/Vortex-moldable-sched/service/run_hpo.py
    type: execute
  enumerator: i
  input: input_config
  type: for
  yieldToInput: output_config
api: 4.7.0
config:
  mesh: convnext_large
  workflowIterations: 3
constraints:
  budget: 28.78
  chains: 3
  deadline: 145240.68
  tinydaIterations: 7
id: hpo-55045f9a
vars:
- id: input_config
  value:
    batch_size: 64
    epochs: 7
    learning_rate: 0.0298
    model: convnext_large
    momentum: 0.82
    next_trials: 3
