actions:
- actions:
  - inputs:
    - id: config
      var: i
    outputs:
    - id: config_out
      var: output_config
    service: /fsx/Vortex-mid/Vortex-moldable-sched/service/run_hpo.py
    type: execute
  enumerator: i
  input: input_config
  type: for
  yieldToInput: output_config
api: 4.7.0
config:
  mesh: wide_resnet101_2
  workflowIterations: 5
constraints:
  budget: 13.85
  chains: 2
  deadline: 40704.65
  tinydaIterations: 3
id: hpo-62ab8c9c
vars:
- id: input_config
  value:
    batch_size: 32
    epochs: 3
    learning_rate: 0.0744
    model: wide_resnet101_2
    momentum: 0.85
    next_trials: 2
