actions:
- actions:
  - inputs:
    - id: config
      var: i
    outputs:
    - id: config_out
      var: output_config
    service: /fsx/Vortex-mid/Vortex-moldable-sched/service/run_hpo.py
    type: execute
  enumerator: i
  input: input_config
  type: for
  yieldToInput: output_config
api: 4.7.0
config:
  mesh: vgg19
  workflowIterations: 3
constraints:
  budget: 13.09
  chains: 2
  deadline: 58251.64
  tinydaIterations: 9
id: hpo-a7e52a5b
vars:
- id: input_config
  value:
    batch_size: 64
    epochs: 9
    learning_rate: 0.0968
    model: vgg19
    momentum: 0.95
    next_trials: 2
