actions:
- actions:
  - inputs:
    - id: config
      var: i
    outputs:
    - id: config_out
      var: output_config
    service: /fsx/Vortex-mid/Vortex-moldable-sched/service/run_hpo.py
    type: execute
  enumerator: i
  input: input_config
  type: for
  yieldToInput: output_config
api: 4.7.0
config:
  mesh: convnext_large
  workflowIterations: 4
constraints:
  budget: 26.57
  chains: 3
  deadline: 129134.9
  tinydaIterations: 9
id: hpo-e4f890c9
vars:
- id: input_config
  value:
    batch_size: 128
    epochs: 9
    learning_rate: 0.0526
    model: convnext_large
    momentum: 0.81
    next_trials: 3
