actions:
- actions:
  - inputs:
    - id: config
      var: i
    outputs:
    - id: config_out
      var: output_config
    service: /fsx/Vortex-mid/Vortex-moldable-sched/service/run_hpo.py
    type: execute
  enumerator: i
  input: input_config
  type: for
  yieldToInput: output_config
api: 4.7.0
config:
  mesh: vgg19
  workflowIterations: 5
constraints:
  budget: 19.65
  chains: 2
  deadline: 63643.97
  tinydaIterations: 9
id: hpo-c6588e9b
vars:
- id: input_config
  value:
    batch_size: 32
    epochs: 9
    learning_rate: 0.0687
    model: vgg19
    momentum: 0.89
    next_trials: 2
