actions:
- actions:
  - inputs:
    - id: config
      var: i
    outputs:
    - id: config_out
      var: output_config
    service: /fsx/Vortex-mid/Vortex-moldable-sched/service/run_hpo.py
    type: execute
  enumerator: i
  input: input_config
  type: for
  yieldToInput: output_config
api: 4.7.0
config:
  mesh: vgg19
  workflowIterations: 5
constraints:
  budget: 11.96
  chains: 4
  deadline: 3189
  tinydaIterations: 3
id: hpo-76abe507
vars:
- id: input_config
  value:
    batch_size: 128
    epochs: 3
    learning_rate: 0.0613
    model: vgg19
    momentum: 0.83
    next_trials: 4
