Region: eu-north-1

# Head node uses default ParallelCluster Ubuntu 22.04 AMI (no GPU needed)
Image:
  Os: ubuntu2204

HeadNode:
  InstanceType: t3.medium
  Networking:
    SubnetId: subnet-016c0e4a31d8955d7                    # e.g., subnet-098f73921fcc5fbe1
    SecurityGroups:
      - sg-0d61f6325a433891b                 # e.g., sg-0d61f6325a433891b
  Ssh:
    KeyName: hpo-exp                # e.g., hpc-exp
  LocalStorage:
    RootVolume:
      Size: 50
      VolumeType: gp3

Scheduling:
  Scheduler: slurm
  SlurmQueues:
    - Name: gpu-compute
      CapacityType: ONDEMAND
      Image:
        CustomAmi: ami-0bace95aa4cfc84f8     # Deep Learning OSS Nvidia Driver AMI GPU PyTorch 2.7 (Ubuntu 22.04)
      ComputeResources:
        - Name: g4dn-nodes
          InstanceType: g4dn.xlarge
          MinCount: 4                        # All nodes up from start
          MaxCount: 4                        # 4 GPU compute nodes (16 vCPUs)
      Networking:
        SubnetIds:
          - subnet-016c0e4a31d8955d7                   # Same subnet as head node
        SecurityGroups:
          - sg-0d61f6325a433891b
        PlacementGroup:
          Enabled: true                      # Better inter-node bandwidth for Ray/DDP
      ComputeSettings:
        LocalStorage:
          RootVolume:
            Size: 100
            VolumeType: gp3
      CustomActions:
        OnNodeConfigured:
          Script: s3://hpoexp/slurm_compute_setup.sh       # e.g., s3://hpoexp/instance_setup_hpo.sh


SharedStorage:
  - MountDir: /fsx
    Name: fsx-hpo
    StorageType: FsxLustre
    FsxLustreSettings:
      FileSystemId: fs-04a4223998940b3ef               # e.g., fs-04a4223998940b3ef
